// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/microhq/geocode-srv/proto/google/google.proto

/*
Package google is a generated protocol buffer package.

It is generated from these files:
	github.com/microhq/geocode-srv/proto/google/google.proto

It has these top-level messages:
	Point
	Bounds
	AddressComponent
	Geometry
	Result
	GeocodeRequest
	GeocodeResponse
	ReverseRequest
	ReverseResponse
*/
package google

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point struct {
	Lat float64 `protobuf:"fixed64,1,opt,name=lat" json:"lat,omitempty"`
	Lng float64 `protobuf:"fixed64,2,opt,name=lng" json:"lng,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Point) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Point) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type Bounds struct {
	Northeast *Point `protobuf:"bytes,1,opt,name=northeast" json:"northeast,omitempty"`
	Southwest *Point `protobuf:"bytes,2,opt,name=southwest" json:"southwest,omitempty"`
}

func (m *Bounds) Reset()                    { *m = Bounds{} }
func (m *Bounds) String() string            { return proto.CompactTextString(m) }
func (*Bounds) ProtoMessage()               {}
func (*Bounds) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Bounds) GetNortheast() *Point {
	if m != nil {
		return m.Northeast
	}
	return nil
}

func (m *Bounds) GetSouthwest() *Point {
	if m != nil {
		return m.Southwest
	}
	return nil
}

type AddressComponent struct {
	LongName  string   `protobuf:"bytes,1,opt,name=long_name,json=longName" json:"long_name,omitempty"`
	ShortName string   `protobuf:"bytes,2,opt,name=short_name,json=shortName" json:"short_name,omitempty"`
	Types     []string `protobuf:"bytes,3,rep,name=types" json:"types,omitempty"`
}

func (m *AddressComponent) Reset()                    { *m = AddressComponent{} }
func (m *AddressComponent) String() string            { return proto.CompactTextString(m) }
func (*AddressComponent) ProtoMessage()               {}
func (*AddressComponent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddressComponent) GetLongName() string {
	if m != nil {
		return m.LongName
	}
	return ""
}

func (m *AddressComponent) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *AddressComponent) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

type Geometry struct {
	Bounds       *Bounds  `protobuf:"bytes,1,opt,name=bounds" json:"bounds,omitempty"`
	Location     *Point   `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	LocationType string   `protobuf:"bytes,3,opt,name=location_type,json=locationType" json:"location_type,omitempty"`
	Viewport     *Bounds  `protobuf:"bytes,4,opt,name=viewport" json:"viewport,omitempty"`
	PartialMatch bool     `protobuf:"varint,5,opt,name=partial_match,json=partialMatch" json:"partial_match,omitempty"`
	PlaceId      string   `protobuf:"bytes,6,opt,name=place_id,json=placeId" json:"place_id,omitempty"`
	Types        []string `protobuf:"bytes,7,rep,name=types" json:"types,omitempty"`
}

func (m *Geometry) Reset()                    { *m = Geometry{} }
func (m *Geometry) String() string            { return proto.CompactTextString(m) }
func (*Geometry) ProtoMessage()               {}
func (*Geometry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Geometry) GetBounds() *Bounds {
	if m != nil {
		return m.Bounds
	}
	return nil
}

func (m *Geometry) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Geometry) GetLocationType() string {
	if m != nil {
		return m.LocationType
	}
	return ""
}

func (m *Geometry) GetViewport() *Bounds {
	if m != nil {
		return m.Viewport
	}
	return nil
}

func (m *Geometry) GetPartialMatch() bool {
	if m != nil {
		return m.PartialMatch
	}
	return false
}

func (m *Geometry) GetPlaceId() string {
	if m != nil {
		return m.PlaceId
	}
	return ""
}

func (m *Geometry) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

type Result struct {
	AddressComponents []*AddressComponent `protobuf:"bytes,1,rep,name=address_components,json=addressComponents" json:"address_components,omitempty"`
	FormattedAddress  string              `protobuf:"bytes,2,opt,name=formatted_address,json=formattedAddress" json:"formatted_address,omitempty"`
	Geometry          *Geometry           `protobuf:"bytes,3,opt,name=geometry" json:"geometry,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Result) GetAddressComponents() []*AddressComponent {
	if m != nil {
		return m.AddressComponents
	}
	return nil
}

func (m *Result) GetFormattedAddress() string {
	if m != nil {
		return m.FormattedAddress
	}
	return ""
}

func (m *Result) GetGeometry() *Geometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

type GeocodeRequest struct {
	Address    string            `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Components map[string]string `protobuf:"bytes,2,rep,name=components" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Bounds     *Bounds           `protobuf:"bytes,3,opt,name=bounds" json:"bounds,omitempty"`
	Language   string            `protobuf:"bytes,4,opt,name=language" json:"language,omitempty"`
	Region     string            `protobuf:"bytes,5,opt,name=region" json:"region,omitempty"`
}

func (m *GeocodeRequest) Reset()                    { *m = GeocodeRequest{} }
func (m *GeocodeRequest) String() string            { return proto.CompactTextString(m) }
func (*GeocodeRequest) ProtoMessage()               {}
func (*GeocodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GeocodeRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GeocodeRequest) GetComponents() map[string]string {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *GeocodeRequest) GetBounds() *Bounds {
	if m != nil {
		return m.Bounds
	}
	return nil
}

func (m *GeocodeRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *GeocodeRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type GeocodeResponse struct {
	Results []*Result `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	Status  string    `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *GeocodeResponse) Reset()                    { *m = GeocodeResponse{} }
func (m *GeocodeResponse) String() string            { return proto.CompactTextString(m) }
func (*GeocodeResponse) ProtoMessage()               {}
func (*GeocodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GeocodeResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *GeocodeResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReverseRequest struct {
	Latlng       *Point   `protobuf:"bytes,1,opt,name=latlng" json:"latlng,omitempty"`
	PlaceId      string   `protobuf:"bytes,2,opt,name=place_id,json=placeId" json:"place_id,omitempty"`
	Language     string   `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"`
	ResultType   []string `protobuf:"bytes,4,rep,name=result_type,json=resultType" json:"result_type,omitempty"`
	LocationType []string `protobuf:"bytes,5,rep,name=location_type,json=locationType" json:"location_type,omitempty"`
}

func (m *ReverseRequest) Reset()                    { *m = ReverseRequest{} }
func (m *ReverseRequest) String() string            { return proto.CompactTextString(m) }
func (*ReverseRequest) ProtoMessage()               {}
func (*ReverseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReverseRequest) GetLatlng() *Point {
	if m != nil {
		return m.Latlng
	}
	return nil
}

func (m *ReverseRequest) GetPlaceId() string {
	if m != nil {
		return m.PlaceId
	}
	return ""
}

func (m *ReverseRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ReverseRequest) GetResultType() []string {
	if m != nil {
		return m.ResultType
	}
	return nil
}

func (m *ReverseRequest) GetLocationType() []string {
	if m != nil {
		return m.LocationType
	}
	return nil
}

type ReverseResponse struct {
	Results []*Result `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	Status  string    `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *ReverseResponse) Reset()                    { *m = ReverseResponse{} }
func (m *ReverseResponse) String() string            { return proto.CompactTextString(m) }
func (*ReverseResponse) ProtoMessage()               {}
func (*ReverseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ReverseResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ReverseResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Point)(nil), "Point")
	proto.RegisterType((*Bounds)(nil), "Bounds")
	proto.RegisterType((*AddressComponent)(nil), "AddressComponent")
	proto.RegisterType((*Geometry)(nil), "Geometry")
	proto.RegisterType((*Result)(nil), "Result")
	proto.RegisterType((*GeocodeRequest)(nil), "GeocodeRequest")
	proto.RegisterType((*GeocodeResponse)(nil), "GeocodeResponse")
	proto.RegisterType((*ReverseRequest)(nil), "ReverseRequest")
	proto.RegisterType((*ReverseResponse)(nil), "ReverseResponse")
}

func init() {
	proto.RegisterFile("github.com/microhq/geocode-srv/proto/google/google.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 654 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xef, 0x6a, 0xdb, 0x3e,
	0x14, 0xad, 0xe3, 0xc6, 0x76, 0x6e, 0xfa, 0x6b, 0x53, 0xf1, 0x63, 0x78, 0x19, 0x5b, 0x3b, 0x77,
	0x83, 0x40, 0x99, 0x03, 0x19, 0x83, 0x32, 0x18, 0xfb, 0xc7, 0x28, 0x83, 0x6d, 0x0c, 0xd3, 0xef,
	0x41, 0xb1, 0x35, 0xc7, 0xcc, 0x96, 0x5c, 0x49, 0x4e, 0xc9, 0xcb, 0xec, 0x0d, 0xf6, 0x6c, 0x7b,
	0x84, 0x0d, 0xc9, 0xb2, 0x13, 0x9b, 0x7d, 0xdb, 0x27, 0xeb, 0x9e, 0x2b, 0x5d, 0x9d, 0x7b, 0xee,
	0x91, 0xe1, 0x2a, 0xcd, 0xe4, 0xba, 0x5a, 0x85, 0x31, 0x2b, 0xe6, 0x45, 0x16, 0x73, 0xb6, 0xbe,
	0x9d, 0xa7, 0x84, 0xc5, 0x2c, 0x21, 0xcf, 0x04, 0xdf, 0xcc, 0x4b, 0xce, 0x24, 0x9b, 0xa7, 0x8c,
	0xa5, 0x39, 0x31, 0x9f, 0x50, 0x63, 0xc1, 0x25, 0x0c, 0xbf, 0xb2, 0x8c, 0x4a, 0x34, 0x01, 0x3b,
	0xc7, 0xd2, 0xb7, 0xce, 0xad, 0x99, 0x15, 0xa9, 0xa5, 0x46, 0x68, 0xea, 0x0f, 0x0c, 0x42, 0xd3,
	0xe0, 0x06, 0x9c, 0x77, 0xac, 0xa2, 0x89, 0x40, 0x4f, 0x60, 0x44, 0x19, 0x97, 0x6b, 0x82, 0x45,
	0x7d, 0x66, 0xbc, 0x70, 0x42, 0x5d, 0x28, 0xda, 0x25, 0xd4, 0x2e, 0xc1, 0x2a, 0xb9, 0xbe, 0x23,
	0x42, 0xea, 0x3a, 0x7b, 0xbb, 0xda, 0x44, 0x90, 0xc0, 0xe4, 0x6d, 0x92, 0x70, 0x22, 0xc4, 0x7b,
	0x56, 0x94, 0x8c, 0x12, 0x2a, 0xd1, 0x03, 0x18, 0xe5, 0x8c, 0xa6, 0x4b, 0x8a, 0x0b, 0xa2, 0xeb,
	0x8f, 0x22, 0x4f, 0x01, 0x5f, 0x70, 0x41, 0xd0, 0x43, 0x00, 0xb1, 0x66, 0x5c, 0xd6, 0xd9, 0x81,
	0xce, 0x8e, 0x34, 0xa2, 0xd3, 0xff, 0xc3, 0x50, 0x6e, 0x4b, 0x22, 0x7c, 0xfb, 0xdc, 0x9e, 0x8d,
	0xa2, 0x3a, 0x08, 0x7e, 0x59, 0xe0, 0x5d, 0x13, 0x56, 0x10, 0xc9, 0xb7, 0xe8, 0x0c, 0x9c, 0x95,
	0x6e, 0xc4, 0x70, 0x77, 0xc3, 0xba, 0xaf, 0xc8, 0xc0, 0x28, 0x00, 0x2f, 0x67, 0x31, 0x96, 0x19,
	0xa3, 0x3d, 0xe2, 0x2d, 0x8e, 0x2e, 0xe0, 0xbf, 0x66, 0xbd, 0x54, 0x77, 0xf8, 0xb6, 0x66, 0x72,
	0xd4, 0x80, 0x37, 0xdb, 0x92, 0xa0, 0x0b, 0xf0, 0x36, 0x19, 0xb9, 0x2b, 0x19, 0x97, 0xfe, 0x61,
	0xf7, 0xae, 0x36, 0xa1, 0x2a, 0x95, 0x98, 0xcb, 0x0c, 0xe7, 0xcb, 0x02, 0xcb, 0x78, 0xed, 0x0f,
	0xcf, 0xad, 0x99, 0x17, 0x1d, 0x19, 0xf0, 0xb3, 0xc2, 0xd0, 0x7d, 0xf0, 0xca, 0x1c, 0xc7, 0x64,
	0x99, 0x25, 0xbe, 0xa3, 0x6f, 0x72, 0x75, 0xfc, 0x31, 0xd9, 0x75, 0xec, 0xee, 0x77, 0xfc, 0xc3,
	0x02, 0x27, 0x22, 0xa2, 0xca, 0x25, 0x7a, 0x03, 0x08, 0xd7, 0x12, 0x2f, 0xe3, 0x46, 0x63, 0xd5,
	0xbb, 0x3d, 0x1b, 0x2f, 0x4e, 0xc3, 0xbe, 0xfa, 0xd1, 0x29, 0xee, 0x21, 0x02, 0x5d, 0xc2, 0xe9,
	0x37, 0xc6, 0x0b, 0x2c, 0x25, 0x49, 0x96, 0x26, 0x6d, 0xa4, 0x9f, 0xb4, 0x09, 0x53, 0x08, 0x3d,
	0x05, 0x2f, 0x35, 0x52, 0x6b, 0x51, 0xc6, 0x8b, 0x51, 0xd8, 0x68, 0x1f, 0xb5, 0xa9, 0xe0, 0xb7,
	0x05, 0xc7, 0xd7, 0xb5, 0x4b, 0x23, 0x72, 0x5b, 0x11, 0x21, 0x91, 0x0f, 0x6e, 0x53, 0xbc, 0x9e,
	0x7a, 0x13, 0xa2, 0xd7, 0x00, 0x7b, 0xd4, 0x07, 0x9a, 0xfa, 0x59, 0xd8, 0x3d, 0x1e, 0xee, 0x08,
	0x7f, 0xa0, 0xea, 0xae, 0xbd, 0x23, 0x7b, 0x33, 0xb7, 0xff, 0x3e, 0xf3, 0x29, 0x78, 0x39, 0xa6,
	0x69, 0x85, 0x53, 0xa2, 0x47, 0xa5, 0x2c, 0x67, 0x62, 0x74, 0x0f, 0x1c, 0x4e, 0x52, 0xe5, 0x86,
	0xa1, 0xce, 0x98, 0x68, 0xfa, 0x0a, 0x4e, 0x7a, 0x77, 0xaa, 0x67, 0xf3, 0x9d, 0x6c, 0x0d, 0x7d,
	0xb5, 0x54, 0xe3, 0xd9, 0xe0, 0xbc, 0x6a, 0xac, 0x5a, 0x07, 0x2f, 0x07, 0x57, 0x56, 0xf0, 0x09,
	0x4e, 0xda, 0x0e, 0x44, 0xc9, 0xa8, 0x20, 0xe8, 0x31, 0xb8, 0x5c, 0x0f, 0xad, 0x99, 0x8f, 0x1b,
	0xd6, 0x43, 0x8c, 0x1a, 0x5c, 0x91, 0x11, 0x12, 0xcb, 0xaa, 0x19, 0x80, 0x89, 0x82, 0x9f, 0x16,
	0x1c, 0x47, 0x64, 0x43, 0xb8, 0x68, 0xf5, 0x7c, 0x04, 0x4e, 0x8e, 0xa5, 0x7a, 0xc6, 0xdd, 0x47,
	0x6a, 0xd0, 0x8e, 0xa9, 0x06, 0x5d, 0x53, 0xed, 0xcb, 0x61, 0xf7, 0xe4, 0x38, 0x83, 0x71, 0x4d,
	0xa6, 0x36, 0xfe, 0xa1, 0xb6, 0x1d, 0xd4, 0x90, 0xb1, 0x7d, 0xef, 0x6d, 0x0c, 0xf5, 0x96, 0xce,
	0xdb, 0x50, 0xdd, 0xb7, 0x74, 0xff, 0xb9, 0xfb, 0x05, 0x03, 0xe7, 0x5a, 0xff, 0xd9, 0x50, 0x08,
	0xae, 0x51, 0x15, 0x9d, 0xf4, 0x1c, 0x32, 0x9d, 0x84, 0x3d, 0xc1, 0x83, 0x03, 0xf4, 0xa2, 0x95,
	0x6d, 0x77, 0xac, 0xab, 0xe3, 0x74, 0x12, 0xf6, 0x98, 0x06, 0x07, 0x2b, 0x47, 0xff, 0x41, 0x9f,
	0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x05, 0xb4, 0x83, 0x76, 0x7d, 0x05, 0x00, 0x00,
}
